### ISSUE TITLE
README_Update

### ISSUE THREAD

**Issue by ymp-a** [ymp-a/tokuMemo#52]
## 機能の概要
README更新

## タスク
下記のタスクを達成すれば、Issueは完了です。
- [1] フロー図説明文追記
- [2] こだわりポイントの詳細記述
- [3] codeLinkをymp-aへ修正

**Comment by YoshinoriKobayashi** [comment]
@ymp-a 

<img width="970" alt="スクリーンショット 2022-11-26 9 22 29" src="https://user-images.githubusercontent.com/5963990/204065356-acc5ec42-dc6a-49e0-b32f-bad815985ee1.png">

こだわりの箇所のコードが展開されていないです。リンクの確認をしましょう。

**Comment by YoshinoriKobayashi** [comment]
@ymp-a 

<img width="970" alt="スクリーンショット 2022-11-26 9 25 18" src="https://user-images.githubusercontent.com/5963990/204065421-0fc49186-dc20-4833-bc15-c144ac0e2ea1.png">

前回みたときに、このフロー図に各項目の説明が表であったと思いますが、今はなくなりました？

**Comment by YoshinoriKobayashi** [comment]
@ymp-a 
細かな箇所ですが、次のように修正したほうが言葉がわかりやすいです。
太字の箇所です。

登録した最安値などの情報をカテゴリ、店舗毎にすぐ**に**チェックできます。
登録した商品情報をカテゴリ、ショップ**の**２つのTagで管理できます。

**Comment by ymp-a** [comment]
@YoshinoriKobayashi 
レビューいただいたのがmainブランチだと思います。
更新したReadMeはこちらです→　https://github.com/ymp-a/tokuMemo/blob/README_Update/README.md
- 太字部分の修正をしました。

**Comment by FromF** [comment]
先ほど話した内容です。

## リンクが唐突で？？になる
1. About Mermaidと書かれているが、ピンとこない。
例えば「Mermaidについて詳細はこちらから確認できます。」とかにするとかいい
<img width="794" alt="スクリーンショット 2022-11-27 16 54 36" src="https://user-images.githubusercontent.com/10681462/204124908-aa18063d-3e64-40ae-baf1-4c5f4c34112d.png">

2. note トクメモアプリの使い方も違和感がある
こちらもGoogle検索結果のような感じにするといい。noteっていう単語が先頭だとメモ書きなのかなって思ってしまう。
<img width="319" alt="スクリーンショット 2022-11-27 16 56 31" src="https://user-images.githubusercontent.com/10681462/204124965-e3141c38-3479-41e7-8121-176c91e752ab.png">
<img width="633" alt="スクリーンショット 2022-11-27 16 57 21" src="https://user-images.githubusercontent.com/10681462/204124989-ef67f046-99eb-4a6d-a420-f240ed832eb2.png">

3. AppStoreのリンクもアイコンにした方がいい
